[book]
authors = ["ld3zian"]
language = "en"
src = "src"
title = "ldez book"

[preprocessor.alerts]

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
additional-css = ["./mdbook-admonish.css"]
